export const palette = {
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    orange: '#c67c4e',
    orange1: '#f36e1b',
    grey: '#9db2ce',
    grey1: '#f1f2f6',
    grey2: 'rgba(52, 52, 52, 0.8)',
    grey3: '#d9d9d9',
    blue: '#386bf6',
    blue1: '#2f3542',
    brown: '#826969',
    yellow: '#ffa801',
    yellow1: '#ffd32a',
    green: '#05c46b',
    green1: '#0be881',
    green2: '#63d52d',
    red: '#ff3f34',
    red1: '#d52d2d',
}

export const colors = {
    white: palette.white,
    black: palette.black,
    transparent: palette.transparent,
    orange: palette.orange,
    orange1: palette.orange1,
    grey: palette.grey,
    grey1: palette.grey1,
    grey2: palette.grey2,
    grey3: palette.grey3,
    blue: palette.blue,
    blue1: palette.blue1,
    brown: palette.brown,
    yellow: palette.yellow,
    yellow1: palette.yellow1,
    green: palette.green,
    green1: palette.green1,
    green2: palette.green2,
    red: palette.red,
    red1: palette.red1,
}