export const palette = {
    white: '#ffffff',
    black: '#000000',
    transparent: 'transparent',
    orange: '#c67c4e',
    orange1: '#f36e1b',
    grey: '#9db2ce',
    grey1: '#f1f2f6',
    blue: '#386bf6',
    blue1: '#2f3542',
    brown: '#826969',
    yellow: '#ffa801',
    yellow1: '#ffd32a',
    green: '#05c46b',
    red: '#ff3f34',
}

export const colors = {
    white: palette.white,
    black: palette.black,
    transparent: palette.transparent,
    orange: palette.orange,
    orange1: palette.orange1,
    grey: palette.grey,
    grey1: palette.grey1,
    blue: palette.blue,
    blue1: palette.blue1,
    brown: palette.brown,
    yellow: palette.yellow,
    yellow1: palette.yellow1,
    green: palette.green,
    red: palette.red,
}