export const labelEn = {
  GENERAL: {
    ABOUT: 'About',
    BTN_MAP: 'Map',
    BTN_DETAIL: 'Detail',
    BTN_EDIT: 'Edit',
    NO_DATA: 'No data',
    REJECT_REASON: 'Type reason of rejection',
  },
  DIALOG: {
    OK: 'OK',
    CANCEL: 'CANCEL',
    ERROR_MESSAGE: 'Error message',
    SUCCESS_MESSAGE: 'Success message',
    WARNING_MESSAGE: 'Warning message',
    LOGOUT: 'Are you sure to log out?',
    DEL_LOVED: 'Are you sure to delete this loved place',
  },
  CREATE_EDIT_DEST: {
    CREATE: 'Create destination',
    CREATE_LABEL: 'Create',
    EDIT_LABEL: 'Edit place',
    UPDATE_LABEL: 'Update',
    RESUBMIT: 'Resubmit',
    LIST: 'List',
    NAME_VI: 'Destination name (VI)',
    NAME_EN: 'Destination name (EN)',
    DESC_VI: 'Description (VI)',
    DESC_EN: 'Description (EN)',
    LAT: 'Latitude',
    LON: 'Longitude',
    CHOOSE_TYPES: 'Choose types',
    CAMERA_CANCELED: 'User cancelled camera',
    CAMERA_ERROR: 'Error from camera',
    PICKER_CANCELED: 'User cancelled image picker',
    PICKER_ERROR: 'Cannot upload image',
    SELECT_TYPES: 'Select the type of place',
    CHOOSE: 'Choose',
    ERROR_MESSAGE: 'Error message',
    CF_RESUBMIT: 'Are you sure to resubmit this request to admin?',
    ERROR: {
      MT_IMAGE: 'Please provide at least one image',
      MT_TYPES: 'Please provide at least one destination type',
      MT_DEST_NAME_VI: 'Please provide name for Vietnamese',
      MT_DEST_NAME_EN: 'Please provide name for English',
      MT_DEST_DESC_VI: 'Please provide description for Vietnamese',
      MT_DEST_DESC_EN: 'Please provide description for English',
      MT_LAT: 'Please provide latitude of destination',
      MT_LON: 'Please provide longitude of destination',
      LAT_NUMBER: 'Latitude must be type of number',
      LON_NUMBER: 'Longitude must be type of number',
      CREATE_DEST: 'Create destination failed',
      UPDATE_DEST: 'Edit destination failed',
      RESUBMIT: 'Resubmit request failed',
    },
    SUCCESS: {
      CREATE_DEST: 'Create destination successfully',
      UPDATE_DEST: 'Edit destination successfully',
      RESUBMIT: 'Resubmit request successfully',
    }
  },
  CREATED_PLACES: {
    SCREEN_TITLE: 'Created Places',
    FIND_PLACEHOLDER: 'Find places',
    FILTER_SEARCH_LABEL: 'Select status',
    FILTER_ALL: 'All',
    FILTER_ACCEPTED: 'Accepted',
    FILTER_WAITING: 'Waiting',
    FILTER_REJECTED: 'Rejected',
  },
  LOVE_LIST: {
    TITLE_SCREEN: 'Loved list',
    TOGGLE_NEWEST: 'Newest',
    TOGGLE_OLDEST: 'Oldest',
    BTN_SHOW_MORE: 'Show more',
    COLLAPSE: 'Collapse',
  },
  OUTSTANDING: {
    FIND_PLACEHOLDER: 'Enter to find places',
    FILTER_BTN: 'Filter',
    FILTER_LABEL: 'Select type(s) to search',
    FILTER_CHOOSE: 'Choose',
    TOP_PLACES: 'Top places',
    NEAREST_PLACE: 'Nearest places',
    HOBBY_PLACES: 'For you',
    SHOW_MORE: 'Show more',
    COLLAPSE: 'Collapse',
  },
  PERSONAL: {
    YOUR_PROFILE: 'Your profile',
    INFORMATION: 'Information',
    FIRST_NAME: 'First name',
    LAST_NAME: 'Last name',
    SET_HOBBY: 'Set hobby',
    HOBBY: 'Hobby',
    SAVE: 'Save',
    CHANGE_PWD: 'Change password',
    SETTING: 'Setting',
    LANGUAGUE: 'Language (VI/EN)',
    THEME: 'Theme (Dark/Light)',
    ADVANCED: 'Advanced',
    USERS: 'Users',
    APPROVAL: 'Approval',
    LOG_OUT: 'Log out',
    FILTER_LABEL: 'Select type(s) to search',
    FILTER_CHOOSE: 'Choose',
    ERROR: {
      UPLOAD_AVATAR: 'Upload avatar failed',
      UPDATE_PROFILE: 'Edit profile failed',
    },
    SUCCESS: {
      UPLOAD_AVATAR: 'Upload avatar successfully',
      UPDATE_PROFILE: 'Edit profile successfully',
    },
  },
  CHANGE_PASSWORD: {
    TITLE: 'Change Password',
    CURRENT: 'Current password',
    NEW: 'New password',
    CONFIRM: 'Confirm password',
    CHANGE: 'Change password',
    RESET: 'Reset',
    SUCCESS: 'Change password successfully',
    ERROR: 'Change password failed',
    VALIDATE: 'Invalid input field(s)',
  },
  REVIEW_USER: {
    TITLE: 'Information',
    CHANGE_BTN: 'Change',
    INFORMATION: 'Information',
    FIRST_NAME: 'First name',
    LAST_NAME: 'Last name',
    SET_HOBBY: 'Set hobby',
    LOGIN_HISTORY: 'Login history',
    PLACE_LOVE_HISTORY: 'Loved places',
    SHOW_MORE: 'Show more',
    COLLAPSE: 'Collapse',
    SELECT_TYPES: 'Chọn loại hình du lịch',
    CHOOSE: 'Chọn',
  },
  VIEW_USERS: {
    TITLE: 'Users list',
    FIND_PLACEHOLDER: 'Find users',
    SELECT_STATE: 'Select filtering',
    FILTER_ALL: 'ALL',
    FILTER_LOCK: 'LOCKED',
    FILTER_UNLOCK: 'ACTIVE',
    SHOW_MORE: 'Show more',
    COLLAPSE: 'Collapse',
    CF_LOCK: 'Are you sure to lock user',
    CF_UNLOCK: 'Are you sure to unlock user',
  },
  DETAIL_REQUEST: {
    APPROVE_LIST: 'Approval list',
    TITLE: 'Request detail',
    CREATED_BY: 'Created by:',
    CREATED_TIME: 'Created at:',
    APPROVE: 'Approve',
    REJECT: 'Reject',
    CF_APPROVE: 'Are you sure to approve this request?',
    CF_REJECT: 'Are you sure to reject this request?',
    SUCCESS: {
      APPROVE: "Place's approved, now it's pulbic",
      REJECT: "Place's rejected"
    },
    ERROR: {
      APPROVE: 'Approve failed',
      REJECT: 'Reject failed',
      MISSING_REASON: 'Please type reason of rejection',
    },
  },
  DETAIL_PLACE: {
    TITLE: 'Detail Place',
    COMMENT: 'Comment',
    ENTER_COMMENT: 'Enter your comment',
    GO_MAP: 'Go to map',
    ASK_STAR: 'Let us know how much you like this place?',
    CF_DEL_CMT: 'Are you sure you want to delete this comment?',
    ERROR: {
      DEFAULT: 'Error happened',
    },
    SUCCESS: {
      DEL_CMT: 'Comment deleted',
      EDIT_CMT: 'Comment updated',
    },
  },
  ASK_HOBBY: {
    TITLE: 'Which is your favorite kinds of travel?',
    CONTINUE: 'Continue',
    ERROR: {
      MT_TYPE: 'Require at least one type of travel',
    },
  },
};

export const labelVi = {
  GENERAL: {
    ABOUT: 'Khoảng',
    BTN_MAP: 'Bản đồ',
    BTN_DETAIL: 'Chi tiết',
    BTN_EDIT: 'Sửa',
    NO_DATA: 'Không có dữ liệu',
    REJECT_REASON: 'Nhập lý do từ chối',
  },
  DIALOG: {
    OK: 'Đồng ý',
    CANCEL: 'Hủy bỏ',
    ERROR_MESSAGE: 'Thông báo lỗi',
    SUCCESS_MESSAGE: 'Thành công',
    WARNING_MESSAGE: 'Cảnh báo',
    LOGOUT: 'Bạn có chắc muốn đăng xuất?',
    DEL_LOVED: 'Bạn có chắc muốn xóa địa điểm này khỏi danh sách yêu thích',
  },
  CREATE_EDIT_DEST: {
    CREATE: 'Tạo địa điểm',
    CREATE_LABEL: 'Tạo',
    EDIT_LABEL: 'Sửa địa điểm',
    UPDATE_LABEL: 'Cập nhật',
    RESUBMIT: 'Gửi lại',
    LIST: 'Danh sách',
    NAME_VI: 'Tên địa điểm (VI)',
    NAME_EN: 'Tên địa điểm (EN)',
    DESC_VI: 'Mô tả địa điểm (VI)',
    DESC_EN: 'Mô tả địa điểm (EN)',
    LAT: 'Vĩ độ',
    LON: 'Kinh độ',
    CHOOSE_TYPES: 'Chọn loại hình',
    CAMERA_CANCELED: 'Đã hủy chọn từ camera',
    CAMERA_ERROR: 'Lỗi camera',
    PICKER_CANCELED: 'Đã hủy chọn ảnh từ thư viện',
    PICKER_ERROR: 'Không thể tải ảnh',
    SELECT_TYPES: 'Chọn loại hình du lịch',
    CHOOSE: 'Chọn',
    ERROR_MESSAGE: 'Thông báo lỗi',
    CF_RESUBMIT: 'Bạn có chắc muốn gửi lại yêu cầu cho quản trị viên?',
    ERROR: {
      MT_IMAGE: 'Cần ít nhất một hình ảnh',
      MT_TYPES: 'Cần ít nhất một loại hình du lịch',
      MT_DEST_NAME_VI: 'Thiếu tên địa điểm (Tiếng Việt)',
      MT_DEST_NAME_EN: 'Thiếu tên địa điểm (Tiếng Anh)',
      MT_DEST_DESC_VI: 'Thiếu mô tả địa điểm (Tiếng Việt)',
      MT_DEST_DESC_EN: 'Thiếu mô tả địa điểm (Tiếng Anh)',
      MT_LAT: 'Thiếu vĩ độ của địa điểm',
      MT_LON: 'Thiếu kinh độ của địa điểm',
      LAT_NUMBER: 'Vĩ độ phải là dạng số',
      LON_NUMBER: 'Kinh độ phải là dạng số',
      CREATE_DEST: 'Tạo địa điểm thất bại',
      UPDATE_DEST: 'Cập nhật địa điểm thất bại',
      RESUBMIT: 'Gửi lại yêu cầu thất bại',
    },
    SUCCESS: {
      CREATE_DEST: 'Tạo địa điểm thành công',
      UPDATE_DEST: 'Cập nhật địa điểm thành công',
      RESUBMIT: 'Gửi lại yêu cầu thành công',
    }
  },
  CREATED_PLACES: {
    SCREEN_TITLE: 'Các địa điểm đã tạo',
    FIND_PLACEHOLDER: 'Tìm kiếm địa điểm',
    FILTER_SEARCH_LABEL: 'Chọn trạng thái',
    FILTER_ALL: 'Tất cả',
    FILTER_ACCEPTED: 'Đã duyệt',
    FILTER_WAITING: 'Chờ duyệt',
    FILTER_REJECTED: 'Đã từ chối',
  },
  LOVE_LIST: {
    TITLE_SCREEN: 'Đã thích',
    TOGGLE_NEWEST: 'Mới nhất',
    TOGGLE_OLDEST: 'Cũ nhất',
    BTN_SHOW_MORE: 'Xem thêm',
    COLLAPSE: 'Rút gọn',
  },
  OUTSTANDING: {
    FIND_PLACEHOLDER: 'Nhập để tìm địa điểm',
    FILTER_BTN: 'Bộ lọc',
    FILTER_LABEL: 'Chọn loại hình để tìm kiếm',
    FILTER_CHOOSE: 'Chọn',
    TOP_PLACES: 'Hàng đầu',
    NEAREST_PLACE: 'Lân cận',
    HOBBY_PLACES: 'Dành cho bạn',
    SHOW_MORE: 'Xem thêm',
    COLLAPSE: 'Rút gọn',
  },
  PERSONAL: {
    YOUR_PROFILE: 'Hồ sơ của bạn',
    INFORMATION: 'Thông tin',
    FIRST_NAME: 'Tên',
    LAST_NAME: 'Họ',
    SET_HOBBY: 'Chỉnh sở thích',
    HOBBY: 'Sở thích',
    SAVE: 'Lưu',
    CHANGE_PWD: 'Đổi mật khẩu',
    SETTING: 'Cài đặt',
    LANGUAGUE: 'Ngôn ngữ (VI/EN)',
    THEME: 'Chủ để (Dark/Light)',
    ADVANCED: 'Nâng cao (admin)',
    USERS: 'Người dùng',
    APPROVAL: 'Phê duyệt',
    LOG_OUT: 'Đăng xuất',
    FILTER_LABEL: 'Chọn loại hình để tìm kiếm',
    FILTER_CHOOSE: 'Chọn',
    ERROR: {
      UPLOAD_AVATAR: 'Tải ảnh đại diện thất bại',
      UPDATE_PROFILE: 'Cập nhật thông tin thất bại',
    },
    SUCCESS: {
      UPLOAD_AVATAR: 'Tải ảnh đại diện thành công',
      UPDATE_PROFILE: 'Cập nhật thông tin thành công',
    },
  },
  CHANGE_PASSWORD: {
    TITLE: 'Đổi mật khẩu',
    CURRENT: 'Mật khẩu hiện tại',
    NEW: 'Mật khẩu mới',
    CONFIRM: 'Xác nhận mật khẩu',
    CHANGE: 'Đổi mật khẩu',
    RESET: 'Đặt lại',
    SUCCESS: 'Đổi mật khẩu thành công',
    ERROR: 'Đổi mật khẩu thất bại',
    VALIDATE: 'Ít nhất một thông tin không hợp lệ',
  },
  REVIEW_USER: {
    TITLE: 'Thông tin',
    CHANGE_BTN: 'Cập nhật',
    INFORMATION: 'Thông tin',
    FIRST_NAME: 'Tên',
    LAST_NAME: 'Họ',
    SET_HOBBY: 'Chỉnh sở thích',
    LOGIN_HISTORY: 'Lịch sử đăng nhập',
    PLACE_LOVE_HISTORY: 'Địa điểm yêu thích',
    SHOW_MORE: 'Xem thêm',
    COLLAPSE: 'Rút gọn',
    SELECT_TYPES: 'Chọn loại hình du lịch',
    CHOOSE: 'Chọn',
  },
  VIEW_USERS: {
    TITLE: 'Danh sách người dùng',
    FIND_PLACEHOLDER: 'Nhập để tìm người dùng',
    SELECT_STATE: 'Chọn bộ lọc',
    FILTER_ALL: 'Tất cả',
    FILTER_LOCK: 'Đã khóa',
    FILTER_UNLOCK: 'Chưa xóa',
    SHOW_MORE: 'Xem thêm',
    COLLAPSE: 'Rút gọn',
    CF_LOCK: 'Bạn có chắc muốn khóa',
    CF_UNLOCK: 'Bạn có chắc muốn bỏ khóa',
  },
  DETAIL_REQUEST: {
    APPROVE_LIST: 'Danh sách yêu cầu',
    TITLE: 'Chi tiết yêu cầu',
    CREATED_BY: 'Tạo bởi',
    CREATED_TIME: 'Thời gian tạo',
    APPROVE: 'Duyệt',
    REJECT: 'Từ chối',
    CF_APPROVE: 'Chắc chắn muốn duyệt yêu cầu này?',
    CF_REJECT: 'Chắc chắn muốn từ chối yêu cầu này?',
    SUCCESS: {
      APPROVE: "Địa điểm đã được duyệt",
      REJECT: "Địa điểm đã bị từ chối"
    },
    ERROR: {
      APPROVE: 'Duyệt thất bại',
      REJECT: 'Từ chối thất bại',
      MISSING_REASON: 'Vui lòng nhập lý do từ chối',
    },
  },
  DETAIL_PLACE: {
    TITLE: 'Thông tin địa điểm',
    COMMENT: 'Bình luận',
    ENTER_COMMENT: 'Nhập nội dung bình luận',
    GO_MAP: 'Đến bản đồ',
    ASK_STAR: 'Hãy cho chúng tôi biết đánh giá của bạn về địa điểm nhé!',
    CF_DEL_CMT: 'Chắn chắn muốn xóa bình luận này?',
    ERROR: {
      DEFAULT: 'Có lỗi xảy ra',
    },
    SUCCESS: {
      DEL_CMT: 'Xóa bình luận thành công',
      EDIT_CMT: 'Sửa bình luận thành công',
    },
  },
  ASK_HOBBY: {
    TITLE: 'Hãy chọn loại hình du lịch mà bạn yêu thích',
    CONTINUE: 'Tiếp tục',
    ERROR: {
      MT_TYPE: 'Hãy chọn ít nhất một loại hình du lịch',
    },
  },
};
